// apps/website/components/oria-theme-editor/shadows/shadow-layer-editor.tsx
import type { CSSProperties, ReactElement } from "react";
import type { ShadowLayer } from "@oriatheme/core";
import { previewColor } from "../fields/color-utils";
import { Trash2 } from "lucide-react";
import { interpolate, useEditorCopy } from "@/components/editor-page/editor-i18n";

type LayerKey = "x" | "y" | "blur" | "spread" | "color";
export function ShadowLayerEditor({ layer, index, onChange, onDelete }: { readonly layer: ShadowLayer; readonly index: number; readonly onChange: (layer: ShadowLayer) => void; readonly onDelete: () => void }): ReactElement {
  const copy = useEditorCopy().chrome.shadow;
  const field = (key: LayerKey, wide = false): ReactElement => <label data-wide={wide || undefined}>
    <span>{copy.fields[key]}</span>
    <input aria-label={`${interpolate(copy.layerName, { index: index + 1 })} ${copy.fields[key]}`} value={layer[key]} onChange={event => onChange({ ...layer, [key]: event.target.value })} spellCheck={false} />
  </label>;
  const swatchStyle = { "--oria-editor-color-preview": previewColor(layer.color) } as CSSProperties;

  return <fieldset data-oria-editor-shadow-layer>
    <legend className="oria-editor-visually-hidden">{interpolate(copy.layerName, { index: index + 1 })}</legend>
    <header>
      <span data-oria-editor-shadow-swatch style={swatchStyle} aria-hidden="true" />
      <span><strong>{interpolate(copy.layerName, { index: index + 1 })}</strong><small>{layer.inset ? copy.inner : copy.outer}</small></span>
      <button type="button" onClick={onDelete} aria-label={interpolate(copy.delete, { index: index + 1 })} title={copy.deleteTitle}>
        <Trash2 aria-hidden="true" />
      </button>
    </header>
    <div data-oria-editor-shadow-layer-fields>
      {field("color", true)}
      {field("x")}
      {field("y")}
      {field("blur")}
      {field("spread")}
    </div>
    <label data-oria-editor-shadow-inset>
      <input type="checkbox" checked={Boolean(layer.inset)} onChange={event => onChange({ ...layer, inset: event.target.checked })} />
      <span aria-hidden="true" />
      <strong>{copy.inset}</strong>
    </label>
  </fieldset>;
}

// registry/templates/vue/theme-editor/shadows/ShadowLayerEditor.vue
<script setup lang="ts">
import type { ShadowLayer } from "@oriatheme/core";
import { previewColor } from "../fields/color-utils";
const props = defineProps<{ layer: ShadowLayer; index: number }>();
const emit = defineEmits<{ change: [layer: ShadowLayer]; delete: [] }>();
type LayerKey = "x" | "y" | "blur" | "spread" | "color";
const labels: Readonly<Record<LayerKey, string>> = { color: "Color", x: "X offset", y: "Y offset", blur: "Blur", spread: "Spread" };
const update = (key: LayerKey | "inset", value: string | boolean): void => emit("change", { ...props.layer, [key]: value });
</script>
<template><fieldset data-oria-editor-shadow-layer><legend class="oria-editor-visually-hidden">Layer {{ index + 1 }}</legend><header><span data-oria-editor-shadow-swatch :style="{ '--oria-editor-color-preview': previewColor(layer.color) }" aria-hidden="true" /><span><strong>Layer {{ index + 1 }}</strong><small>{{ layer.inset ? "Inner shadow" : "Outer shadow" }}</small></span><button type="button" :aria-label="`Delete shadow layer ${index + 1}`" title="Delete layer" @click="emit('delete')"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3m-8 0 1 13h8l1-13M10 11v5m4-5v5" /></svg></button></header><div data-oria-editor-shadow-layer-fields><label v-for="key in (['color','x','y','blur','spread'] as const)" :key="key" :data-wide="key === 'color' || undefined"><span>{{ labels[key] }}</span><input :aria-label="`Layer ${index + 1} ${labels[key]}`" :value="layer[key]" spellcheck="false" @input="update(key,($event.target as HTMLInputElement).value)" /></label></div><label data-oria-editor-shadow-inset><input type="checkbox" :checked="Boolean(layer.inset)" @change="update('inset',($event.target as HTMLInputElement).checked)" /><span aria-hidden="true" /><strong>Inset shadow</strong></label></fieldset></template>
