// apps/examples/editor-vue/src/components/oria-theme-editor/fields/ColorField.vue
<script setup lang="ts">
import { computed, toRef } from "vue";
import type { TokenFieldProps } from "../types";
import { useFieldBuffer } from "../composables/useFieldBuffer";
import BaseColorPalette from "./BaseColorPalette.vue";
import { nativeColor, previewColor } from "./color-utils";
import FieldFrame from "./FieldFrame.vue";
const props = defineProps<TokenFieldProps>();
const value = computed(() => typeof props.value === "string" ? props.value : "");
const buffer = useFieldBuffer(toRef(value), item => item, item => item.trim() ? item : undefined, item => props.session.setToken(props.mode, props.field.path, item));
const id = computed(() => `oria-${props.mode}-${props.field.path.replaceAll(".", "-")}`);
</script>
<template><FieldFrame v-bind="props"><div data-oria-editor-color><button type="button" data-oria-editor-color-swatch :aria-label="`Choose ${field.label}`" :style="{ '--oria-editor-color-preview': previewColor(buffer.text.value) }"><input tabindex="-1" type="color" :value="nativeColor(buffer.text.value)" @input="buffer.update(($event.target as HTMLInputElement).value)" /></button><input :id="id" :value="buffer.text.value" :aria-invalid="Boolean(issue)" spellcheck="false" @input="buffer.update(($event.target as HTMLInputElement).value)" /><BaseColorPalette :id="`${id}-base-colors`" :label="field.label" :value="buffer.text.value" @select="buffer.update" /></div></FieldFrame></template>

// apps/website/components/oria-theme-editor/fields/color-field.tsx
import type { CSSProperties, ReactElement } from "react";
import type { TokenFieldProps } from "../types";
import { useFieldBuffer } from "../hooks/use-field-buffer";
import { BaseColorPalette } from "./base-color-palette";
import { nativeColor, previewColor } from "./color-utils";
import { FieldFrame, fieldId } from "./field-frame";
import { interpolate, useEditorCopy } from "@/components/editor-page/editor-i18n";

export function ColorField(props: TokenFieldProps): ReactElement {
  const copy = useEditorCopy().chrome.palette;
  const value = typeof props.value === "string" ? props.value : "";
  const buffer = useFieldBuffer(value, item => item, item => item.trim() ? item : undefined, item => props.session.setToken(props.mode, props.field.path, item));
  const native = nativeColor(buffer.text);
  const preview = previewColor(buffer.text);
  const id = fieldId(props);
  return <FieldFrame props={props}><div data-oria-editor-color>
    <button type="button" data-oria-editor-color-swatch aria-label={interpolate(copy.chooseColor, { label: props.field.label })} style={{ "--oria-editor-color-preview": preview } as CSSProperties}><input tabIndex={-1} type="color" value={native} onChange={event => buffer.setText(event.target.value)} /></button>
    <input id={id} value={buffer.text} aria-invalid={Boolean(props.issue)} onChange={event => buffer.setText(event.target.value)} spellCheck={false} />
    <BaseColorPalette id={`${id}-base-colors`} label={props.field.label} value={buffer.text} onSelect={buffer.setText} />
  </div></FieldFrame>;
}
