// registry/templates/react/theme-editor/fields/editor-select.tsx
import type { ReactElement, SelectHTMLAttributes } from "react";

/** Shared native select chrome with a stable size, chevron, and keyboard behavior. */
export function EditorSelect({ children, ...props }: SelectHTMLAttributes<HTMLSelectElement>): ReactElement {
  return <span data-oria-editor-select>
    <select {...props}>{children}</select>
    <svg viewBox="0 0 20 20" aria-hidden="true"><path d="m6.5 8 3.5 3.5L13.5 8" /></svg>
  </span>;
}

// apps/examples/editor-vue/src/components/oria-theme-editor/fields/EditorSelect.vue
<script setup lang="ts">
defineOptions({ inheritAttrs: false });
const props = defineProps<{ modelValue: string | number }>();
const emit = defineEmits<{ "update:modelValue": [value: string] }>();
</script>

<template><span data-oria-editor-select><select v-bind="$attrs" :value="props.modelValue" @change="emit('update:modelValue', ($event.target as HTMLSelectElement).value)"><slot /></select><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m6.5 8 3.5 3.5L13.5 8" /></svg></span></template>
