// apps/examples/next/app/components/oria-theme-editor/fields/font-weight-field.tsx
import type { ReactElement } from "react";
import type { TokenFieldProps } from "../types";
import { useFieldBuffer } from "../hooks/use-field-buffer";
import { FieldFrame, fieldId } from "./field-frame";
import { LinearSlider } from "./linear-slider";
import { fontWeightSliderRange } from "./slider-ranges";

const numericWeight = (value: string): number => value === "normal" ? 400 : value === "bold" ? 700 : Number(value);

export function FontWeightField(props: TokenFieldProps): ReactElement {
  const value = typeof props.value === "string" ? props.value : "400";
  const buffer = useFieldBuffer(value, item => item, item => /^(?:normal|bold|[1-9]00)$/.test(item) ? item : undefined, item => props.session.setToken(props.mode, props.field.path, item));
  const weight = numericWeight(buffer.text);
  return <FieldFrame props={props}><div data-oria-editor-range data-has-slider>
    <LinearSlider label={`${props.field.label} slider`} value={Number.isFinite(weight) ? weight : 400} minimum={fontWeightSliderRange.minimum} maximum={fontWeightSliderRange.maximum} step={fontWeightSliderRange.step} onValueChange={next => buffer.setText(String(next))} />
    <input id={fieldId(props)} value={buffer.text} inputMode="numeric" onChange={event => buffer.setText(event.target.value)} />
  </div></FieldFrame>;
}

// apps/examples/editor-vue/src/components/oria-theme-editor/fields/FontWeightField.vue
<script setup lang="ts">
import { computed, toRef } from "vue";
import type { TokenFieldProps } from "../types";
import { useFieldBuffer } from "../composables/useFieldBuffer";
import FieldFrame from "./FieldFrame.vue";
import LinearSlider from "./LinearSlider.vue";
import { fontWeightSliderRange } from "./slider-ranges";
const props = defineProps<TokenFieldProps>();
const value = computed(() => typeof props.value === "string" ? props.value : "400");
const buffer = useFieldBuffer(toRef(value), item => item, item => /^(?:normal|bold|[1-9]00)$/.test(item) ? item : undefined, item => props.session.setToken(props.mode, props.field.path, item));
const weight = computed(() => buffer.text.value === "normal" ? 400 : buffer.text.value === "bold" ? 700 : Number(buffer.text.value));
const id = computed(() => `oria-${props.mode}-${props.field.path.replaceAll(".", "-")}`);
</script>
<template><FieldFrame v-bind="props"><div data-oria-editor-range data-has-slider><LinearSlider :label="`${field.label} slider`" :value="Number.isFinite(weight) ? weight : 400" :minimum="fontWeightSliderRange.minimum" :maximum="fontWeightSliderRange.maximum" :step="fontWeightSliderRange.step" @value-change="next => buffer.update(String(next))" /><input :id="id" :value="buffer.text.value" inputmode="numeric" @input="buffer.update(($event.target as HTMLInputElement).value)" /></div></FieldFrame></template>
