// apps/examples/editor-vue/src/components/oria-theme-editor/overlays/ConfirmationDialog.vue
<script setup lang="ts">
import { ref, watch } from "vue";
const props = withDefaults(defineProps<{ open: boolean; title: string; description: string; confirmLabel: string; cancelLabel?: string; destructive?: boolean }>(), { cancelLabel: "Cancel", destructive: true });
const emit = defineEmits<{ confirm: []; cancel: [] }>();
const dialog = ref<HTMLDialogElement>();
watch(() => props.open, open => { const element = dialog.value; if (!element) return; if (open && !element.open) element.showModal(); else if (!open && element.open) element.close(); }, { immediate: true, flush: "post" });
</script>
<template><dialog ref="dialog" data-oria-editor-confirmation :aria-label="title" @cancel.prevent="emit('cancel')"><div data-oria-editor-confirmation-panel><div data-oria-editor-confirmation-icon aria-hidden="true">!</div><div data-oria-editor-confirmation-copy><h2>{{ title }}</h2><p>{{ description }}</p></div><div data-oria-editor-confirmation-actions><button type="button" @click="emit('cancel')">{{ cancelLabel }}</button><button type="button" :data-oria-editor-confirm="destructive ? 'destructive' : 'primary'" autofocus @click="emit('confirm')">{{ confirmLabel }}</button></div></div></dialog></template>

// apps/examples/next/app/components/oria-theme-editor/overlays/confirmation-dialog.tsx
import { useEffect, useId, useRef } from "react";
import type { ReactElement } from "react";

export interface ConfirmationDialogProps {
  readonly open: boolean;
  readonly title: string;
  readonly description: string;
  readonly confirmLabel: string;
  readonly cancelLabel?: string;
  readonly destructive?: boolean;
  readonly onConfirm: () => void;
  readonly onCancel: () => void;
}

export function ConfirmationDialog({ open, title, description, confirmLabel, cancelLabel = "Cancel", destructive = true, onConfirm, onCancel }: ConfirmationDialogProps): ReactElement {
  const dialog = useRef<HTMLDialogElement>(null);
  const titleId = useId();
  const descriptionId = useId();

  useEffect(() => {
    const element = dialog.current;
    if (!element) return;
    if (open && !element.open) element.showModal();
    if (!open && element.open) element.close();
  }, [open]);

  return <dialog ref={dialog} data-oria-editor-confirmation aria-labelledby={titleId} aria-describedby={descriptionId} onCancel={event => { event.preventDefault(); onCancel(); }}>
    <div data-oria-editor-confirmation-panel>
      <div data-oria-editor-confirmation-icon aria-hidden="true">!</div>
      <div data-oria-editor-confirmation-copy><h2 id={titleId}>{title}</h2><p id={descriptionId}>{description}</p></div>
      <div data-oria-editor-confirmation-actions>
        <button type="button" onClick={onCancel}>{cancelLabel}</button>
        <button type="button" data-oria-editor-confirm={destructive ? "destructive" : "primary"} autoFocus onClick={onConfirm}>{confirmLabel}</button>
      </div>
    </div>
  </dialog>;
}
